# -*- coding: utf-8 -*-
"""phase0_canonical.py - Phase 0: canonical numbers + manifest for gear fatigue paper.

Usage:
  python phase0_canonical.py           # regenerate output/canonical_numbers.json + output/MANIFEST.txt
  python phase0_canonical.py --check   # verify committed files still match current outputs (exit 0/1)

The manifest is deterministic (no timestamps) and excludes itself, so
`python phase0_canonical.py --check` after reproduce.sh detects any data drift.
"""
import csv, hashlib, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "output")
CSV = os.path.join(HERE, "\u6570\u5b57\u6765\u6e90-\u9f7f\u8f6e\u75b2\u52b3v4.8.csv")

def parse_val(s):
    s = (s or "").strip()
    if not s:
        return s
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        pass
    return s

def build_canonical():
    rows = []
    with open(CSV, encoding="utf-8-sig", newline="") as f:
        for r in csv.DictReader(f):
            rows.append(r)
    labels = json.load(open(os.path.join(OUT, "labels.json"), encoding="utf-8"))
    keys = [k for k in labels if not k.startswith("_")]
    if len(keys) != len(rows):
        raise SystemExit("key/row mismatch: %d vs %d" % (len(keys), len(rows)))
    canon = {
        "_meta": {
            "generated_by": "phase0_canonical.py",
            "paper_version": "v5.0",
            "n_numbers": len(keys),
            "source": "\u6570\u5b57\u6765\u6e90-\u9f7f\u8f6e\u75b2\u52b3v4.8.csv (generated by generate_labels_v3.py from output/*.json)",
            "schema": {
                "value": "canonical value as printed in the paper (parsed int/float, else string)",
                "section": "paper section / table where the number appears",
                "note": "claim or variable description",
                "source_file": "JSON or PDF file the number is sourced from",
                "source_key": "key/path inside the source file",
                "match": "AUTO (pulled from JSON) / COMPUTED (derived) / LIT (literature PDF) / LIT+JSON",
            },
        }
    }
    for k, r in zip(keys, rows):
        canon[k] = {
            "value": parse_val(r.get("Value in Paper", "")),
            "section": r.get("Paper Section", ""),
            "note": r.get("Claim/Number", ""),
            "source_file": r.get("Source File", ""),
            "source_key": r.get("Source Key", ""),
            "match": r.get("Match", ""),
        }
    return canon

def build_manifest():
    files = sorted(
        f for f in os.listdir(OUT)
        if os.path.isfile(os.path.join(OUT, f)) and f != "_legacy" and f != "MANIFEST.txt"
    )
    lines = [
        "# MANIFEST - output/ file inventory (MD5 checksums)",
        "# purpose: consistency anchor; deterministic; run `python phase0_canonical.py --check`",
        "#          after reproduce.sh to detect any data drift.",
        "# format: <md5>  <size bytes>  <filename>",
        "",
    ]
    for f in files:
        p = os.path.join(OUT, f)
        h = hashlib.md5(open(p, "rb").read()).hexdigest()
        sz = os.path.getsize(p)
        lines.append("%s  %10d  %s" % (h, sz, f))
    return "\n".join(lines) + "\n", len(files)

def main():
    if "--check" in sys.argv:
        canon = build_canonical()
        manifest, nfiles = build_manifest()
        ok = True
        p1 = os.path.join(OUT, "canonical_numbers.json")
        p2 = os.path.join(OUT, "MANIFEST.txt")
        if not os.path.exists(p1) or json.load(open(p1, encoding="utf-8", newline="")) != canon:
            print("[FAIL] canonical_numbers.json drifted")
            ok = False
        else:
            print("[OK] canonical_numbers.json matches")
        if not os.path.exists(p2) or open(p2, encoding="utf-8", newline="").read() != manifest:
            print("[FAIL] MANIFEST.txt drifted")
            ok = False
        else:
            print("[OK] MANIFEST.txt matches")
        print("RESULT:", "PASS" if ok else "FAIL")
        sys.exit(0 if ok else 1)
    else:
        # write canonical FIRST, then build the manifest over the freshly
        # written canonical so the manifest is never one generation stale
        with open(os.path.join(OUT, "canonical_numbers.json"), "w", encoding="utf-8", newline="\n") as f:
            json.dump(build_canonical(), f, indent=2, ensure_ascii=False)
        manifest, nfiles = build_manifest()
        with open(os.path.join(OUT, "MANIFEST.txt"), "w", encoding="utf-8", newline="\n") as f:
            f.write(manifest)
        print("canonical_numbers.json: %d numbers" % (len(build_canonical()) - 1))
        print("MANIFEST.txt: %d files" % nfiles)

if __name__ == "__main__":
    main()
